import type { ArchiveRecord } from "./types";
import { archiveGalleries } from "./archive-media";

export const archives: ArchiveRecord[] = [
  {
    slug: "frequency-fest",
    title: "Frequency Fest Vol. 1",
    archiveLabel: "Permanent feature",
    dateLabel: "July 10, 2026",
    dateIso: "2026-07-10",
    locationLabel: "Club SAW · 67 Nicholas St, Ottawa",
    summary: "A two-stage mini festival at Club SAW, pairing an open-air room with a late-night main stage.",
    story: [
      "Frequency Fest Vol. 1 brought Chefnier, LX, Niko Couture, Alex Jimenez, and Danford to the open-air stage, with Return of the Jaded, Seung, Setou & Senyo, Sebastian Couture, and Emblem inside on the main stage.",
      "Club SAW hosted the July 10 takeover at 67 Nicholas Street. Boukine Productions built the open-air production and sound, Red Bull Canada supported the night, and Catherine Archambault and Szeming Wu were thanked for capturing it.",
      "All fifteen frames from Catherine Archambault’s published event recap are preserved here. Twelve standout originals from the supplied Club SAW photo set extend that edit across the open-air stage, the indoor room, the crew, and the dance floor.",
    ],
    eventSlug: null,
    gallery: archiveGalleries["frequency-fest"],
    gallerySlotCount: archiveGalleries["frequency-fest"].length,
    coverImageIndex: 0,
    featured: true,
    featureImageIndices: [0, 8, 3],
    photoCredit: "@catherine.archambault · additional supplied set uncredited",
    sourceNote: "The announcement confirms the venue, date, two-stage format, and lineup. Catherine Archambault is credited on the published gallery source; the later thank-you post also credits Szeming Wu for event photography. Twelve additional originals were selected from the Club SAW photo folder supplied directly for this site update.",
    sourceLinks: [
      { label: "Event announcement", href: "https://www.instagram.com/p/DZBHCnzn8Sx/" },
      { label: "Original event recap", href: "https://www.instagram.com/p/Das9FdvCfZt/" },
      { label: "Partner and crew thanks", href: "https://www.instagram.com/p/Da3O0kLJWvP/" },
    ],
    draft: true,
  },
  {
    slug: "frequency-shift-001",
    title: "Frequency Shift 001",
    archiveLabel: "FS / 001",
    dateLabel: "May 31, 2025",
    dateIso: "2025-05-31",
    locationLabel: "Ottawa, Canada",
    summary: "Ottawa’s debut Frequency Shift—the Saturday the collective described as only the beginning.",
    story: [
      "The first lineup announcement called Ottawa’s house heads to the floor under a simple phrase: for the love of beats. The recap that followed thanked every dancer and framed the debut as the start of something still to come.",
      "This edit preserves all twenty stills from the original recap, photographed by Blue Chapel Lamb. Promotional artwork stays outside the gallery so the archive remains a record of the room itself.",
    ],
    eventSlug: null,
    gallery: archiveGalleries["frequency-shift-001"],
    gallerySlotCount: archiveGalleries["frequency-shift-001"].length,
    coverImageIndex: 0,
    photoCredit: "@bluechapellamb",
    sourceNote: "Matched to 001 through the debut announcement and the account's first event recap.",
    sourceLinks: [
      { label: "Debut lineup reel", href: "https://www.instagram.com/reel/DJKXF1Yyz6V/" },
      { label: "Original event recap", href: "https://www.instagram.com/p/DKe8HNiOT1M/" },
    ],
    draft: true,
  },
  {
    slug: "frequency-shift-002",
    title: "Frequency Shift 002",
    archiveLabel: "FS / 002",
    dateLabel: "July 2025",
    dateIso: "2025-07",
    locationLabel: "Ottawa, Canada",
    summary: "An eleven-still black-and-white recap, published with a quick invitation to do it again the following Saturday.",
    story: [
      "The original caption keeps the focus on the feeling of the night and asks the room, simply, whether it should meet again the next Saturday. The 002 label comes from the feed and highlight sequence rather than a number stated in that caption.",
      "The source carousel contains one video; this archive preserves its eleven original still photographs and leaves the motion asset outside the image edit.",
    ],
    eventSlug: null,
    gallery: archiveGalleries["frequency-shift-002"],
    gallerySlotCount: archiveGalleries["frequency-shift-002"].length,
    coverImageIndex: 0,
    photoCredit: null,
    sourceNote: "Assigned to 002 from the publication sequence and the adjacent dated event captions.",
    sourceLinks: [
      { label: "Original event recap", href: "https://www.instagram.com/p/DMTH-bCMKX6/" },
    ],
    draft: true,
  },
  {
    slug: "frequency-shift-003",
    title: "Frequency Shift 003",
    archiveLabel: "FS / 003",
    dateLabel: "July 26, 2025",
    dateIso: "2025-07-26",
    locationLabel: "GRIDWRKS · Ottawa",
    summary: "Frequency Shift joined Off Grid Saturdays for OGS018 at GRIDWRKS; Seb Belanger, Jrise, and LX’s sets were later released in full.",
    story: [
      "Ahead of OGS018, Frequency Shift described its intent in its own words: channel raw underground energy into Ottawa, make room for freedom and self-expression, and build a community connected through music rather than another routine club night.",
      "LX, Seb Belanger, and Jrise carried the July 26 collaboration. Both partner recaps locate the event at GRIDWRKS and remember the room for keeping its energy high all night.",
      "Off Grid later published full-set releases for Seb Belanger, Jrise, and LX, extending the OGS018 record beyond the room and its still-photo recap.",
      "Sixteen photographs from the two recaps are preserved here. Video clips from the mixed-media carousel remain outside the still-image edit.",
    ],
    eventSlug: null,
    gallery: archiveGalleries["frequency-shift-003"],
    gallerySlotCount: archiveGalleries["frequency-shift-003"].length,
    coverImageIndex: 1,
    photoCredit: null,
    sourceNote: "The July 26 date, GRIDWRKS location, collaboration, and lineup are stated directly across the partner announcement and recaps; three later Off Grid posts document the full-set releases.",
    sourceLinks: [
      { label: "Collaboration statement", href: "https://www.instagram.com/p/DMdwuDnvnKH/" },
      { label: "Event-night collaboration post", href: "https://www.instagram.com/p/DMlUeeKvdNg/" },
      { label: "Frequency Shift recap", href: "https://www.instagram.com/p/DNEDMbduITH/" },
      { label: "Off Grid recap", href: "https://www.instagram.com/p/DMvmQsbPOkr/" },
      { label: "Seb Belanger full-set release", href: "https://www.instagram.com/p/DPAOdRxDzCV/" },
      { label: "Jrise full-set release", href: "https://www.instagram.com/p/DPNJv_KEW9M/" },
      { label: "LX full-set release", href: "https://www.instagram.com/p/DPXgfzYEZX9/" },
    ],
    draft: true,
  },
  {
    slug: "frequency-shift-004",
    title: "Frequency Shift 004",
    archiveLabel: "FS / 004",
    dateLabel: "January 3, 2026",
    dateIso: "2026-01-03",
    locationLabel: "GRIDWRKS · Ottawa",
    summary: "A January 3 run-it-back at GRIDWRKS with Off Grid Saturdays, Seb Belanger, Matia Dosen, Arden, and Maggie Tipenko.",
    story: [
      "Announced first as a January 3 run-it-back, OGS041 reunited Frequency Shift and Off Grid Saturdays for a musical journey from Seb Belanger, Matia Dosen, Arden, and Maggie Tipenko. The event post and Instagram location place the collaboration at GRIDWRKS.",
      "The follow-up recap thanked everyone who came and remembered the night as a magical start to the year. Two clean event-night frames selected from that official recap preserve the red-laser room, glow-stick crowd, and Frequency Shift roundel without mixing in the pre-event campaign carousels.",
    ],
    eventSlug: null,
    gallery: archiveGalleries["frequency-shift-004"],
    gallerySlotCount: archiveGalleries["frequency-shift-004"].length,
    coverImageIndex: 0,
    photoCredit: null,
    sourceNote: "The save-the-date Reel identifies the January 3 run-it-back; the event-night post confirms OGS041, the lineup, and GRIDWRKS. The 004 label follows the account’s numbered highlight sequence. The two gallery images are selected still frames from the official January 8 recap Reel; no photographer or videographer is credited in its public caption.",
    sourceLinks: [
      { label: "Save-the-date announcement", href: "https://www.instagram.com/reel/DSfs0EuDE7I/" },
      { label: "Event and lineup", href: "https://www.instagram.com/p/DTDmFUQkbsa/" },
      { label: "Lineup preview", href: "https://www.instagram.com/p/DTBopfakTDL/" },
      { label: "Official event recap", href: "https://www.instagram.com/reel/DTQ3_47EldH/" },
    ],
    draft: true,
  },
  {
    slug: "frequency-shift-005",
    title: "Frequency Shift 005",
    archiveLabel: "FS / 005",
    dateLabel: "June 5, 2026",
    dateIso: "2026-06-05",
    locationLabel: "GRIDWRKS · 221 Rideau St, Ottawa",
    summary: "Frequency Shift's first solo event at GRIDWRKS, built around a high-energy local lineup.",
    story: [
      "Sophiaxfay, Seb Belanger b2b Dylan McIntosh, Vantedge, and Nate Adams supplied the sounds for the June 5 event.",
      "The 19+ standalone night opened at 10 PM at 221 Rideau Street. The feed records both the lineup announcement and final call, but no public still-photo recap has followed yet.",
    ],
    eventSlug: null,
    gallery: [],
    gallerySlotCount: 12,
    coverImageIndex: 0,
    photoCredit: null,
    sourceNote: "The event details are explicit; 005 follows the numbered highlight sequence rather than the named collaboration dates. The announcement, final-call Reel, public posts, partner accounts, and tagged material yielded campaign media but no verifiable June 5 event-night stills or recap.",
    sourceLinks: [
      { label: "Event announcement", href: "https://www.instagram.com/p/DYvaHn_DjMZ/" },
      { label: "Final event call", href: "https://www.instagram.com/reel/DZI133bBfK4/" },
    ],
    draft: true,
  },
  {
    slug: "world-cup",
    title: "World Cup",
    archiveLabel: "Special / 01",
    dateLabel: "June 18, 2026",
    dateIso: "2026-06-18",
    locationLabel: "GRIDWRKS · Ottawa",
    summary: "Concept 168 turned World Cup season into a global dancefloor, with Frequency Shift taking over the GRIDWRKS main room.",
    story: [
      "The main-room programme was built around sounds that cross borders and a simple invitation to represent your flag and culture. Seb Belanger b2b Gab Balladelli, Camille Hendricks, and Fawcy supplied the Frequency Shift sets.",
      "More Than Piano carried the theme into the side room with DJ Maz, Ttrills, Best Rae, and Wallxce. The free-entry edition ran from 9 PM to 2 AM at GRIDWRKS.",
      "All ten photographs from the event recap are included here; flyers and the promotional carousel stay outside the documentary edit.",
    ],
    eventSlug: null,
    gallery: archiveGalleries["world-cup"],
    gallerySlotCount: archiveGalleries["world-cup"].length,
    coverImageIndex: 0,
    photoCredit: null,
    sourceNote: "The event title, collaborators, venue, and recap are identified directly by the original posts.",
    sourceLinks: [
      { label: "Event details", href: "https://www.instagram.com/p/DZvGRnrEfKv/" },
      { label: "Original event recap", href: "https://www.instagram.com/p/DaBDdIyjhBX/" },
    ],
    draft: true,
  },
  {
    slug: "solstice",
    title: "Solstice",
    archiveLabel: "Special / 02",
    dateLabel: "May 22, 2026",
    dateIso: "2026-05-22",
    locationLabel: "City At Night · 222 Slater St, Ottawa",
    summary: "A May 22 Solstice takeover at City At Night, framed as a new orbit into summer.",
    story: [
      "Solstice introduced the collaboration as a new orbit and invited the room to shift into summer energy with Frequency Shift. City At Night billed the Friday programme as a full takeover at 222 Slater Street.",
      "The event was 19+ with valid physical ID required. Partner and event-day posts add green-laser campaign imagery, but all were published before the May 22 night began. The gallery therefore remains open for original event photographs rather than relabelling campaign artwork as documentary media.",
    ],
    eventSlug: null,
    gallery: [],
    gallerySlotCount: 12,
    coverImageIndex: 0,
    photoCredit: null,
    sourceNote: "The Solstice announcement confirms the date and collaboration; City At Night confirms the venue address and takeover format. A public posts, Reels, partner, and tagged-content pass found additional pre-event and event-day campaign posts, but no verifiable May 22 event-night recap.",
    sourceLinks: [
      { label: "Event announcement", href: "https://www.instagram.com/p/DX72dPuRmwQ/" },
      { label: "Venue week listing", href: "https://www.instagram.com/p/DYflEe0kT5V/" },
      { label: "Partner preview", href: "https://www.instagram.com/p/DYirCB8jPDy/" },
      { label: "Event-day post", href: "https://www.instagram.com/p/DYpz9HyDyZq/" },
    ],
    draft: true,
  },
  {
    slug: "dopamine",
    title: "Dopamine",
    archiveLabel: "Special / 03",
    dateLabel: "March 17, 2026",
    dateIso: "2026-03-17",
    locationLabel: "City At Night · 222 Slater St, Ottawa",
    summary: "Frequency Shift x Dopamine claimed St. Patrick’s Day Tuesday at City At Night, with doors from 8 PM.",
    story: [
      "Dopamine announced its return as a St. Patrick’s Day collaboration with Frequency Shift, pairing an 8 PM opening with an all-night Jägerbomb special. City At Night’s weekly bill confirmed the Tuesday takeover at 222 Slater Street.",
      "This gallery contains all twenty still photographs from the original event recap, credited in the source post to Mystic Does Media.",
    ],
    eventSlug: null,
    gallery: archiveGalleries.dopamine,
    gallerySlotCount: archiveGalleries.dopamine.length,
    coverImageIndex: 0,
    photoCredit: "@mysticdoesmedia",
    sourceNote: "The announcement and venue listing confirm the 8 PM opening and address; the recap confirms the date, collaboration, location, and photographer.",
    sourceLinks: [
      { label: "Event announcement", href: "https://www.instagram.com/p/DVbaBnVACTU/" },
      { label: "Venue week listing", href: "https://www.instagram.com/p/DV9aAL3FZoQ/" },
      { label: "Original event recap", href: "https://www.instagram.com/p/DWUtWzUjo6R/" },
    ],
    draft: true,
  },
];

export function getArchive(slug: string) {
  return archives.find((entry) => entry.slug === slug);
}
