import type { ArchiveRecord } from "./types";
import { archiveGalleries } from "./archive-media";

export const archives: ArchiveRecord[] = [
  {
    slug: "frequency-fest",
    title: "Frequency Fest Vol. 1",
    archiveLabel: "Permanent feature",
    dateLabel: "July 10, 2026",
    dateIso: "2026-07-10",
    locationLabel: "Club SAW · 67 Nicholas St, Ottawa",
    summary: "Our first two-stage mini festival at Club SAW, pairing an open-air room with a late-night main stage.",
    story: [
      "We built Frequency Fest Vol. 1 across two stages: Chefnier, LX, Niko Couture, Alex Jimenez, and Danford in the open air, then Return of the Jaded, Seung, Setou & Senyo, Sebastian Couture, and Emblem inside on the main stage.",
      "We took over Club SAW at 67 Nicholas Street on July 10. Boukine Productions built the open-air production and sound, Red Bull Canada supported the night, and Catherine Archambault and Szeming Wu captured it.",
      "The gallery moves through the open-air stage, the indoor room, the crew, and the dancefloor, with fifteen frames from Catherine Archambault and twelve more standouts from our Club SAW set.",
    ],
    eventSlug: null,
    gallery: archiveGalleries["frequency-fest"],
    coverImageIndex: 0,
    featured: true,
    featureImageIndices: [0, 8, 3],
    photoCredit: "@catherine.archambault · additional supplied set uncredited",
    sourceNote: "The announcement confirms the venue, date, two-stage format, and lineup. Catherine Archambault is credited on the published gallery source; the later thank-you post also credits Szeming Wu for event photography. Twelve additional originals were selected from the Club SAW photo folder supplied directly for this site update.",
    sourceLinks: [
      { label: "Event announcement", href: "https://www.instagram.com/p/DZBHCnzn8Sx/" },
      { label: "Original event recap", href: "https://www.instagram.com/p/Das9FdvCfZt/" },
      { label: "Partner and crew thanks", href: "https://www.instagram.com/p/Da3O0kLJWvP/" },
    ],
  },
  {
    slug: "frequency-shift-001",
    title: "Frequency Shift 001",
    archiveLabel: "FS / 001",
    dateLabel: "May 31, 2025",
    dateIso: "2025-05-31",
    locationLabel: "Ottawa, Canada",
    summary: "Our first Frequency Shift in Ottawa—the Saturday that started everything.",
    story: [
      "For our first night, we called Ottawa’s house heads to the floor with one simple line: for the love of beats. Every dancer who showed up made the debut feel like the start of something bigger.",
      "Blue Chapel Lamb photographed the room. These twenty stills keep the focus there—on the people, the movement, and the night itself.",
    ],
    eventSlug: null,
    gallery: archiveGalleries["frequency-shift-001"],
    coverImageIndex: 0,
    photoCredit: "@bluechapellamb",
    sourceNote: "Matched to 001 through the debut announcement and the account's first event recap.",
    sourceLinks: [
      { label: "Debut lineup reel", href: "https://www.instagram.com/reel/DJKXF1Yyz6V/" },
      { label: "Original event recap", href: "https://www.instagram.com/p/DKe8HNiOT1M/" },
    ],
  },
  {
    slug: "frequency-shift-002",
    title: "Frequency Shift 002",
    archiveLabel: "FS / 002",
    dateLabel: "July 2025",
    dateIso: "2025-07",
    locationLabel: "Ottawa, Canada",
    summary: "Eleven black-and-white frames from a night that left us ready to do it again the following Saturday.",
    story: [
      "We left 002 with one simple question for the room: should we do it again next Saturday? The feeling was already there.",
      "These eleven black-and-white stills hold onto the faces, movement, and close-up energy of the night.",
    ],
    eventSlug: null,
    gallery: archiveGalleries["frequency-shift-002"],
    coverImageIndex: 0,
    photoCredit: null,
    sourceNote: "Assigned to 002 from the publication sequence and the adjacent dated event captions.",
    sourceLinks: [
      { label: "Original event recap", href: "https://www.instagram.com/p/DMTH-bCMKX6/" },
    ],
  },
  {
    slug: "frequency-shift-003",
    title: "Frequency Shift 003",
    archiveLabel: "FS / 003",
    dateLabel: "July 26, 2025",
    dateIso: "2025-07-26",
    locationLabel: "GRIDWRKS · Ottawa",
    summary: "We joined Off Grid Saturdays for OGS018 at GRIDWRKS, with Seb Belanger, Jrise, and LX in the room.",
    story: [
      "Going into OGS018, we wanted to bring raw underground energy into Ottawa and make room for freedom, self-expression, and connection through music—not another routine club night.",
      "LX, Seb Belanger, and Jrise carried the July 26 collaboration at GRIDWRKS, and the room kept the energy high all night.",
      "Off Grid later released the full sets from Seb Belanger, Jrise, and LX, giving us a way back into the music after the night was over.",
      "These sixteen photographs bring the two sides of the collaboration together in one place.",
    ],
    eventSlug: null,
    gallery: archiveGalleries["frequency-shift-003"],
    coverImageIndex: 1,
    photoCredit: null,
    sourceNote: "The July 26 date, GRIDWRKS location, collaboration, and lineup are stated directly across the partner announcement and recaps; three later Off Grid posts document the full-set releases.",
    sourceLinks: [
      { label: "Collaboration statement", href: "https://www.instagram.com/p/DMdwuDnvnKH/" },
      { label: "Event-night collaboration post", href: "https://www.instagram.com/p/DMlUeeKvdNg/" },
      { label: "Frequency Shift recap", href: "https://www.instagram.com/p/DNEDMbduITH/" },
      { label: "Off Grid recap", href: "https://www.instagram.com/p/DMvmQsbPOkr/" },
      { label: "Seb Belanger full-set release", href: "https://www.instagram.com/p/DPAOdRxDzCV/" },
      { label: "Jrise full-set release", href: "https://www.instagram.com/p/DPNJv_KEW9M/" },
      { label: "LX full-set release", href: "https://www.instagram.com/p/DPXgfzYEZX9/" },
    ],
  },
  {
    slug: "frequency-shift-004",
    title: "Frequency Shift 004",
    archiveLabel: "FS / 004",
    dateLabel: "January 3, 2026",
    dateIso: "2026-01-03",
    locationLabel: "GRIDWRKS · Ottawa",
    summary: "We ran it back at GRIDWRKS with Off Grid Saturdays, Seb Belanger, Matia Dosen, Arden, and Maggie Tipenko.",
    story: [
      "For OGS041, we reunited with Off Grid Saturdays at GRIDWRKS and ran it back with Seb Belanger, Matia Dosen, Arden, and Maggie Tipenko.",
      "Everyone who came gave us a magical start to the year. Two event-night frames hold onto the red lasers, glow-stick crowd, and Frequency Shift roundel.",
    ],
    eventSlug: null,
    gallery: archiveGalleries["frequency-shift-004"],
    coverImageIndex: 0,
    photoCredit: null,
    sourceNote: "The save-the-date Reel identifies the January 3 run-it-back; the event-night post confirms OGS041, the lineup, and GRIDWRKS. The 004 label follows the account’s numbered highlight sequence. The two gallery images are selected still frames from the official January 8 recap Reel; no photographer or videographer is credited in its public caption.",
    sourceLinks: [
      { label: "Save-the-date announcement", href: "https://www.instagram.com/reel/DSfs0EuDE7I/" },
      { label: "Event and lineup", href: "https://www.instagram.com/p/DTDmFUQkbsa/" },
      { label: "Lineup preview", href: "https://www.instagram.com/p/DTBopfakTDL/" },
      { label: "Official event recap", href: "https://www.instagram.com/reel/DTQ3_47EldH/" },
    ],
  },
  {
    slug: "frequency-shift-005",
    title: "Frequency Shift 005",
    archiveLabel: "FS / 005",
    dateLabel: "June 5, 2026",
    dateIso: "2026-06-05",
    locationLabel: "GRIDWRKS · 221 Rideau St, Ottawa",
    summary: "Our first solo event at GRIDWRKS, built around a high-energy local lineup.",
    story: [
      "Sophiaxfay, Seb Belanger b2b Dylan McIntosh, Vantedge, and Nate Adams brought the sound for our June 5 night.",
      "We opened at 10 PM at 221 Rideau Street for our first solo GRIDWRKS event. The lineup announcement and final call are linked below.",
    ],
    eventSlug: null,
    gallery: [],
    coverImageIndex: 0,
    photoCredit: null,
    sourceNote: "The announcement and final-call Reel confirm the date, venue, first-solo-event framing, and lineup. The 005 label follows the numbered highlight sequence.",
    sourceLinks: [
      { label: "Event announcement", href: "https://www.instagram.com/p/DYvaHn_DjMZ/" },
      { label: "Final event call", href: "https://www.instagram.com/reel/DZI133bBfK4/" },
    ],
  },
  {
    slug: "world-cup",
    title: "World Cup",
    archiveLabel: "Special / 01",
    dateLabel: "June 18, 2026",
    dateIso: "2026-06-18",
    locationLabel: "GRIDWRKS · Ottawa",
    summary: "For Concept 168, we turned the GRIDWRKS main room into a global dancefloor.",
    story: [
      "We built the main room around sounds that cross borders and invited everyone to represent their flag and culture. Seb Belanger b2b Gab Balladelli, Camille Hendricks, and Fawcy held down the Frequency Shift side.",
      "More Than Piano carried the theme into the side room with DJ Maz, Ttrills, Best Rae, and Wallxce. The free-entry edition ran from 9 PM to 2 AM at GRIDWRKS.",
      "These ten photographs stay with the dancefloor and the people who filled it.",
    ],
    eventSlug: null,
    gallery: archiveGalleries["world-cup"],
    coverImageIndex: 0,
    photoCredit: null,
    sourceNote: "The event title, collaborators, venue, and recap are identified directly by the original posts.",
    sourceLinks: [
      { label: "Event details", href: "https://www.instagram.com/p/DZvGRnrEfKv/" },
      { label: "Original event recap", href: "https://www.instagram.com/p/DaBDdIyjhBX/" },
    ],
  },
  {
    slug: "solstice",
    title: "Solstice",
    archiveLabel: "Special / 02",
    dateLabel: "May 22, 2026",
    dateIso: "2026-05-22",
    locationLabel: "City At Night · 222 Slater St, Ottawa",
    summary: "Our May 22 Solstice takeover at City At Night—a new orbit into summer.",
    story: [
      "For Solstice, we took over City At Night at 222 Slater Street and invited the room to shift into summer energy with us.",
      "The event was 19+ with valid physical ID required. We’ve kept the original announcements linked below.",
    ],
    eventSlug: null,
    gallery: [],
    coverImageIndex: 0,
    photoCredit: null,
    sourceNote: "The Solstice announcement confirms the date and collaboration; City At Night confirms the venue and takeover format. All linked images were published before the event.",
    sourceLinks: [
      { label: "Event announcement", href: "https://www.instagram.com/p/DX72dPuRmwQ/" },
      { label: "Venue week listing", href: "https://www.instagram.com/p/DYflEe0kT5V/" },
      { label: "Partner preview", href: "https://www.instagram.com/p/DYirCB8jPDy/" },
      { label: "Event-day post", href: "https://www.instagram.com/p/DYpz9HyDyZq/" },
    ],
  },
  {
    slug: "dopamine",
    title: "Dopamine",
    archiveLabel: "Special / 03",
    dateLabel: "March 17, 2026",
    dateIso: "2026-03-17",
    locationLabel: "City At Night · 222 Slater St, Ottawa",
    summary: "We joined Dopamine for a St. Patrick’s Day Tuesday at City At Night, with doors from 8 PM.",
    story: [
      "We joined Dopamine for a St. Patrick’s Day takeover at City At Night, with an 8 PM opening and an all-night Jägerbomb special at 222 Slater Street.",
      "Mystic Does Media photographed the night. All twenty stills are here.",
    ],
    eventSlug: null,
    gallery: archiveGalleries.dopamine,
    coverImageIndex: 0,
    photoCredit: "@mysticdoesmedia",
    sourceNote: "The announcement and venue listing confirm the 8 PM opening and address; the recap confirms the date, collaboration, location, and photographer.",
    sourceLinks: [
      { label: "Event announcement", href: "https://www.instagram.com/p/DVbaBnVACTU/" },
      { label: "Venue week listing", href: "https://www.instagram.com/p/DV9aAL3FZoQ/" },
      { label: "Original event recap", href: "https://www.instagram.com/p/DWUtWzUjo6R/" },
    ],
  },
];

export function getArchive(slug: string) {
  return archives.find((entry) => entry.slug === slug);
}
