import type { ArchiveRecord } from "./types";
import { archiveGalleries } from "./archive-media";

export const archives: ArchiveRecord[] = [
  {
    slug: "frequency-shift-001",
    title: "Frequency Shift 001",
    archiveLabel: "FS / 001",
    dateLabel: "May 31, 2025",
    dateIso: "2025-05-31",
    locationLabel: "Ottawa, Canada",
    summary: "The debut Frequency Shift: twenty photographs from the night that started the series.",
    story: [
      "The first Frequency Shift established the project in Ottawa with a packed room, a close dancefloor, and the raw house-driven energy that would define the events that followed.",
      "This edit preserves every still from the original debut recap. Promotional artwork was excluded so the archive remains a record of the event itself.",
    ],
    eventSlug: null,
    gallery: archiveGalleries["frequency-shift-001"],
    gallerySlotCount: archiveGalleries["frequency-shift-001"].length,
    coverImageIndex: 0,
    photoCredit: "@bluechapellamb",
    sourceNote: "Matched to 001 through the debut announcement and the account's first event recap.",
    sourceLinks: [
      { label: "Original event recap", href: "https://www.instagram.com/p/DKe8HNiOT1M/" },
    ],
    draft: true,
  },
  {
    slug: "frequency-shift-002",
    title: "Frequency Shift 002",
    archiveLabel: "FS / 002",
    dateLabel: "July 2025",
    dateIso: "2025-07",
    locationLabel: "Ottawa, Canada",
    summary: "An eleven-frame black-and-white record of Frequency Shift's second chapter.",
    story: [
      "Published between the debut recap and the explicitly dated July 26 collaboration, this standalone Frequency Shift gallery captures the second event in the numbered sequence.",
      "The source carousel contains one video; this archive includes its eleven original still photographs and leaves the motion asset out of the image edit.",
    ],
    eventSlug: null,
    gallery: archiveGalleries["frequency-shift-002"],
    gallerySlotCount: archiveGalleries["frequency-shift-002"].length,
    coverImageIndex: 0,
    photoCredit: null,
    sourceNote: "Assigned to 002 from the publication sequence and the adjacent dated event captions.",
    sourceLinks: [
      { label: "Original event recap", href: "https://www.instagram.com/p/DMTH-bCMKX6/" },
    ],
    draft: true,
  },
  {
    slug: "frequency-shift-003",
    title: "Frequency Shift 003",
    archiveLabel: "FS / 003",
    dateLabel: "July 26, 2025",
    dateIso: "2025-07-26",
    locationLabel: "Off Grid Saturdays · Ottawa",
    summary: "Frequency Shift joined Off Grid Saturdays for OGS018, documented across two recap carousels.",
    story: [
      "LX, Seb Belanger, and Jrise carried the July 26 collaboration. The original captions identify the event as Frequency Shift x Off Grid Saturdays and OGS018.",
      "Sixteen photographs from the two partner recaps are preserved here. Video clips from the mixed-media carousel were intentionally excluded.",
    ],
    eventSlug: null,
    gallery: archiveGalleries["frequency-shift-003"],
    gallerySlotCount: archiveGalleries["frequency-shift-003"].length,
    coverImageIndex: 1,
    photoCredit: null,
    sourceNote: "The July 26 date, collaboration, and lineup are stated directly in the original captions.",
    sourceLinks: [
      { label: "Frequency Shift recap", href: "https://www.instagram.com/p/DNEDMbduITH/" },
      { label: "Off Grid recap", href: "https://www.instagram.com/p/DMvmQsbPOkr/" },
    ],
    draft: true,
  },
  {
    slug: "frequency-shift-004",
    title: "Frequency Shift 004",
    archiveLabel: "FS / 004",
    dateLabel: "January 3, 2026",
    dateIso: "2026-01-03",
    locationLabel: "Off Grid Saturdays · Ottawa",
    summary: "Frequency Shift and Off Grid Saturdays ran it back for the first gathering of 2026.",
    story: [
      "The event brought Seb Belanger, Matia Dosen, Arden, and Maggie Tipenko together for OGS041.",
      "The public recap is video-only. This contact sheet remains open until original event stills are supplied; promotional graphics and extracted video frames have not been substituted for photography.",
    ],
    eventSlug: null,
    gallery: [],
    gallerySlotCount: 12,
    coverImageIndex: 0,
    photoCredit: null,
    sourceNote: "The date and collaboration are explicit; 004 follows the account's numbered highlight sequence. No public still-photo recap was available.",
    sourceLinks: [
      { label: "Event recap", href: "https://www.instagram.com/p/DTQ3_47EldH/" },
    ],
    draft: true,
  },
  {
    slug: "frequency-shift-005",
    title: "Frequency Shift 005",
    archiveLabel: "FS / 005",
    dateLabel: "June 5, 2026",
    dateIso: "2026-06-05",
    locationLabel: "GRIDWRKS · 221 Rideau St, Ottawa",
    summary: "Frequency Shift's first solo event at GRIDWRKS, built around a high-energy local lineup.",
    story: [
      "Sophiaxfay, Seb Belanger b2b Dylan McIntosh, Vantedge, and Nate Adams supplied the sounds for the June 5 event.",
      "The public feed currently contains announcements and artist features, but no event-photo recap. The gallery remains a placeholder rather than mixing promotional artwork into the documentary archive.",
    ],
    eventSlug: null,
    gallery: [],
    gallerySlotCount: 12,
    coverImageIndex: 0,
    photoCredit: null,
    sourceNote: "The event details are explicit; 005 follows the numbered highlight sequence rather than the named collaboration dates. No public still-photo recap was available.",
    sourceLinks: [
      { label: "Event announcement", href: "https://www.instagram.com/p/DYvaHn_DjMZ/" },
    ],
    draft: true,
  },
  {
    slug: "world-cup",
    title: "World Cup",
    archiveLabel: "Special / 01",
    dateLabel: "June 18, 2026",
    dateIso: "2026-06-18",
    locationLabel: "City Gridwrks · Ottawa",
    summary: "A global dancefloor for Concept 168, with Frequency Shift taking over the main room.",
    story: [
      "The World Cup special paired a cross-border music theme with sets from Seb Belanger b2b Gab Balladelli, Camille Hendricks, and Fawcy in the main room.",
      "All ten photographs from the event recap are included here; flyers and the preceding promotional carousel were excluded.",
    ],
    eventSlug: null,
    gallery: archiveGalleries["world-cup"],
    gallerySlotCount: archiveGalleries["world-cup"].length,
    coverImageIndex: 0,
    photoCredit: null,
    sourceNote: "The event title, collaborators, venue, and recap are identified directly by the original posts.",
    sourceLinks: [
      { label: "Event details", href: "https://www.instagram.com/p/DZvGRnrEfKv/" },
      { label: "Original event recap", href: "https://www.instagram.com/p/DaBDdIyjhBX/" },
    ],
    draft: true,
  },
  {
    slug: "solstice",
    title: "Solstice",
    archiveLabel: "Special / 02",
    dateLabel: "May 22, 2026",
    dateIso: "2026-05-22",
    locationLabel: "City At Night · Ottawa",
    summary: "Frequency Shift took over Solstice as the room moved into its summer orbit.",
    story: [
      "The collaboration landed at City At Night on May 22 as a dedicated Frequency Shift takeover.",
      "Only announcements and promotional media are public on the account. The gallery remains open for original event photographs rather than presenting campaign artwork as a recap.",
    ],
    eventSlug: null,
    gallery: [],
    gallerySlotCount: 12,
    coverImageIndex: 0,
    photoCredit: null,
    sourceNote: "The date and venue are explicit in the event posts; no public still-photo recap was available.",
    sourceLinks: [
      { label: "Event announcement", href: "https://www.instagram.com/p/DX72dPuRmwQ/" },
    ],
    draft: true,
  },
  {
    slug: "dopamine",
    title: "Dopamine",
    archiveLabel: "Special / 03",
    dateLabel: "March 17, 2026",
    dateIso: "2026-03-17",
    locationLabel: "City At Night · Ottawa",
    summary: "Frequency Shift x Dopamine brought a St. Patrick's Day charge to City At Night.",
    story: [
      "The March 17 collaboration turned an off-night Tuesday into a packed St. Patrick's Day dancefloor.",
      "This gallery contains all twenty still photographs from the original event recap, credited in the source post to Mystic Does Media.",
    ],
    eventSlug: null,
    gallery: archiveGalleries.dopamine,
    gallerySlotCount: archiveGalleries.dopamine.length,
    coverImageIndex: 0,
    photoCredit: "@mysticdoesmedia",
    sourceNote: "The event, date, venue, collaboration, and photographer are stated directly in the recap caption.",
    sourceLinks: [
      { label: "Original event recap", href: "https://www.instagram.com/p/DWUtWzUjo6R/" },
    ],
    draft: true,
  },
];

export function getArchive(slug: string) {
  return archives.find((entry) => entry.slug === slug);
}
